# Generated by Django 4.2.4 on 2023-08-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="3081a19a0c734fd2b9228f3c303c586c",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_wallet_id", models.CharField(default="", max_length=80)),
                ("receiver_wallet_id", models.CharField(default="", max_length=80)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "new_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "old_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("description", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="wal_8ed070392c9a4cf3b71ad20fedd6872b",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(default="", max_length=100)),
                (
                    "transfer_recipient_code",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
            ],
        ),
    ]
